export const CategoryItems = [
  {
    categoryTitle: "MEN",
    categories: [
      {
        id: 0,
        title: "New Arrivals",
        names: [{ name: "New Summer Arrivals" }],
      },
      {
        title: "Featured",
        names: [
          { name: "Golf Essentials" },
          { name: "Best Sellers" },
          { name: "Jordan" },
          { name: "Matching Sets" },
          { name: "Customize with Nike by You" },
          { name: "Sale - Up to 40% Off" },
        ],
      },
      {
        id: 1,
        title: "All Shoes",
        names: [
          { name: "Lifestyle" },
          { name: "Air Max" },
          { name: "Air Force 1" },
          { name: "Dunks & Blazers" },
          { name: "Basketball" },
          { name: "Running" },
          { name: "Soccer" },
          { name: "Golf" },
          { name: "SB" },
          { name: "Training & Gym" },
          { name: "Slides" },
        ],
      },
      {
        id: 2,
        title: "All Clothing",
        names: [
          { name: "Jordan" },
          { name: "Workout" },
          { name: "Big & Tall" },
          { name: "Tops & T-Shirts" },
          { name: "Hoodies & Sweatshirts" },
          { name: "Jackets & Vests" },
          { name: "Pants & Tights" },
          { name: "Shorts" },
          { name: "Underwear" },
          { name: "Socks" },
        ],
      },
      {
        id: 3,
        title: "Shop By Sport",
        names: [
          { name: "Golf" },
          { name: "Soccer" },
          { name: "Basketball" },
          { name: "Tennis" },
          { name: "Baseball" },
          { name: "Football" },
          { name: "Running" },
          { name: "Training & Gym" },
          { name: "Cross Country" },
          { name: "Yoga" },
          { name: "Pickleball" },
          { name: "Swim" },
        ],
      },
    ],
  },
  {
    categoryTitle: "WOMEN",
    categories: [
      {
        id: 0,
        title: "New Arrivals",
        names: [{ name: "New Summer Arrivals" }],
      },
      {
        id: 1,
        title: "Featured",
        names: [
          { name: "Golf Essentials" },
          { name: "Best Sellers" },
          { name: "Jordan" },
          { name: "Matching Sets" },
          { name: "Customize with Nike by You" },
          { name: "Sale - Up to 40% Off" },
        ],
      },
      {
        id: 2,
        title: "All Shoes",
        names: [
          { name: "Lifestyle" },
          { name: "Air Max" },
          { name: "Air Force 1" },
          { name: "Basketball" },
          { name: "Running" },
          { name: "Soccer" },
          { name: "SB" },
          { name: "Training & Gym" },
        ],
      },
      {
        id: 3,
        title: "All Clothing",
        names: [
          { name: "Workout" },
          { name: "Big & Tall" },
          { name: "Tops & T-Shirts" },
          { name: "Hoodies & Sweatshirts" },
          { name: "Jackets & Vests" },
          { name: "Pants & Tights" },
          { name: "Shorts" },
          { name: "Underwear" },
          { name: "Socks" },
        ],
      },
      {
        id: 4,
        title: "Shop By Sport",
        names: [
          { name: "Golf" },
          { name: "Soccer" },
          { name: "Basketball" },
          { name: "Tennis" },
          { name: "Football" },
          { name: "Running" },
          { name: "Training & Gym" },
          { name: "Yoga" },
          { name: "Swim" },
        ],
      },
    ],
  },
  {
    categoryTitle: "KIDS",
    categories: [
      {
        id: 0,
        title: "New Arrivals",
        names: [{ name: "New Summer Arrivals" }],
      },
      {
        id: 1,
        title: "Featured",
        names: [
          { name: "Golf Essentials" },
          { name: "Best Sellers" },
          { name: "Jordan" },
          { name: "Matching Sets" },
          { name: "Customize with Nike by You" },
          { name: "Sale - Up to 40% Off" },
        ],
      },
      {
        id: 2,
        title: "All Shoes",
        names: [{ name: "Lifestyle" }],
      },
      {
        id: 3,
        title: "All Clothing",
        names: [
          { name: "Jordan" },
          { name: "Workout" },
          { name: "Big & Tall" },
          { name: "Tops & T-Shirts" },
          { name: "Hoodies & Sweatshirts" },
          { name: "Jackets & Vests" },
          { name: "Pants & Tights" },
          { name: "Shorts" },
          { name: "Underwear" },
          { name: "Socks" },
        ],
      },
      {
        id: 4,
        title: "Shop By Sport",
        names: [{ name: "Soccer" }, { name: "Basketball" }, { name: "Tennis" }],
      },
    ],
  },
  {
    categoryTitle: "NEW&FEATURED",
    categories: [
      {
        id: 0,
        title: "New Arrivals",
        names: [{ name: "New Summer Arrivals" }],
      },
    ],
  },
  {
    categoryTitle: "SALES",
    categories: [
      {
        id: 1,
        title: "All Shoes",
        names: [
          { name: "Lifestyle" },
          { name: "Air Max" },
          { name: "Air Force 1" },
          { name: "Dunks & Blazers" },
          { name: "Basketball" },
          { name: "Running" },
          { name: "Soccer" },
          { name: "Golf" },
          { name: "SB" },
          { name: "Training & Gym" },
          { name: "Slides" },
        ],
      },
      {
        id: 2,
        title: "All Clothing",
        names: [
          { name: "Jordan" },
          { name: "Workout" },
          { name: "Big & Tall" },
          { name: "Tops & T-Shirts" },
          { name: "Hoodies & Sweatshirts" },
          { name: "Jackets & Vests" },
          { name: "Pants & Tights" },
          { name: "Shorts" },
          { name: "Underwear" },
          { name: "Socks" },
        ],
      },
      {
        id: 3,
        title: "Shop By Sport",
        names: [
          { name: "Golf" },
          { name: "Soccer" },
          { name: "Basketball" },
          { name: "Tennis" },
          { name: "Baseball" },
          { name: "Football" },
          { name: "Running" },
          { name: "Training & Gym" },
          { name: "Cross Country" },
          { name: "Yoga" },
          { name: "Pickleball" },
          { name: "Swim" },
        ],
      },
    ],
  },
  {
    categoryTitle: "ACCESORIES",
    categories: [
      {
        id: 0,
        title: "All Shoes",
        names: [
          { name: "Lifestyle" },
          { name: "Air Max" },
          { name: "Air Force 1" },
          { name: "Dunks & Blazers" },
          { name: "Basketball" },
          { name: "Running" },
          { name: "Soccer" },
          { name: "Golf" },
          { name: "SB" },
          { name: "Training & Gym" },
          { name: "Slides" },
        ],
      },
      {
        id: 1,
        title: "All Clothing",
        names: [
          { name: "Jordan" },
          { name: "Workout" },
          { name: "Big & Tall" },
          { name: "Tops & T-Shirts" },
          { name: "Hoodies & Sweatshirts" },
          { name: "Jackets & Vests" },
          { name: "Pants & Tights" },
          { name: "Shorts" },
          { name: "Underwear" },
          { name: "Socks" },
        ],
      },
      {
        id: 2,
        title: "Shop By Sport",
        names: [
          { name: "Golf" },
          { name: "Soccer" },
          { name: "Basketball" },
          { name: "Tennis" },
          { name: "Baseball" },
          { name: "Football" },
          { name: "Running" },
          { name: "Training & Gym" },
          { name: "Cross Country" },
          { name: "Yoga" },
          { name: "Pickleball" },
          { name: "Swim" },
        ],
      },
    ],
  },
];
